/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FedralRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.FederalBankEnterprise;
import Business.Enterprise.LogisticsEnterprise;
import Business.Network.Network;
import Business.Organization.LogisticOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BankToFederalBankWorkRequest;
import Business.WorkQueue.FederalToLogisticsWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.EmployeeRole.EmployeeWorkAreaJPanel;

/**
 *
 * @author keval
 */
public class RequestToLogisticJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestToLogistic
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private BankToFederalBankWorkRequest bankToFederalBankWorkRequest;
    private FederalToLogisticsWorkRequest federalToLogisticsWorkRequest;
    private EcoSystem business;

    RequestToLogisticJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, BankToFederalBankWorkRequest bankToFederalBankWorkRequest, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        txtFedralNetwork.setText(String.valueOf(bankToFederalBankWorkRequest.getAmount()));
        lbtBankName.setText(bankToFederalBankWorkRequest.getBankEnterprise().getName());
        txtPickedAmmount.setText(String.valueOf(bankToFederalBankWorkRequest.getAmountToPickUp()));
        this.bankToFederalBankWorkRequest = bankToFederalBankWorkRequest;
        this.federalToLogisticsWorkRequest = new FederalToLogisticsWorkRequest();
        this.business = business;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtFedralNetwork = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPickedAmmount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnRequestLogistci = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lbtBankName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("Ammount to be delivered");

        txtFedralNetwork.setEditable(false);
        txtFedralNetwork.setBackground(new java.awt.Color(255, 255, 255));
        txtFedralNetwork.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel3.setText("Bank Name");

        txtPickedAmmount.setEditable(false);
        txtPickedAmmount.setBackground(new java.awt.Color(255, 255, 255));
        txtPickedAmmount.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setText("Ammount to be picked up");

        btnRequestLogistci.setBackground(new java.awt.Color(255, 255, 255));
        btnRequestLogistci.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnRequestLogistci.setText("Request Logistic");
        btnRequestLogistci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestLogistciActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(lbtBankName, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(775, 775, 775)
                        .addComponent(btnRequestLogistci, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(467, 467, 467)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFedralNetwork, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                    .addComponent(txtPickedAmmount))))))
                .addGap(312, 312, 312))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbtBankName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFedralNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPickedAmmount, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRequestLogistci, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(421, 421, 421))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRequestLogistciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestLogistciActionPerformed
        int a = 0, b = 0;

        try {
            a = Integer.parseInt(txtFedralNetwork.getText());
            b = Integer.parseInt(txtPickedAmmount.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter a valid number.");
        }

        if (a < 0 || b < 0) {
            JOptionPane.showMessageDialog(null, "Please enter a positive number.");
        } else {
            federalToLogisticsWorkRequest.setAmount(a);
            federalToLogisticsWorkRequest.setAmountToPickUp(b);
            federalToLogisticsWorkRequest.setStatus("sent");

            federalToLogisticsWorkRequest.setFedralBankEnterprise((FederalBankEnterprise) enterprise);
            federalToLogisticsWorkRequest.setBankEnterprise(bankToFederalBankWorkRequest.getBankEnterprise());
            federalToLogisticsWorkRequest.setSender(userAccount);
            bankToFederalBankWorkRequest.setReceiver(userAccount);
            bankToFederalBankWorkRequest.setStatus("Completed");
            federalToLogisticsWorkRequest.setRequestDate(LocalDate.now());

            for (Network network : business.getNetworkList()) {
                //            if(network.getEnterpriseDirectory().getEnterpriseList().contains(enterprise)){
                for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                    if (enterprise instanceof LogisticsEnterprise) {
                        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                            if (organization instanceof LogisticOrganization) {
                                organization.getWorkQueue().getWorkRequestList().add((WorkRequest) federalToLogisticsWorkRequest);
                            }
                        }
                    }
                }
            }
        }

        JOptionPane.showMessageDialog(null, "Request to Logistics sent");
        
    }//GEN-LAST:event_btnRequestLogistciActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequestLogistci;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbtBankName;
    private javax.swing.JTextField txtFedralNetwork;
    private javax.swing.JTextField txtPickedAmmount;
    // End of variables declaration//GEN-END:variables
}
