/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EmployeeRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.EmployeeOrganization;
import Business.Organization.IncomeTaxOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.TokenTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author raunak
 */
public class ProcessRequestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private TokenTestWorkRequest tokenTestWorkRequest;
    

    /**
     * Creates new form RequestLabTestJPanel
     */
    public ProcessRequestJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, TokenTestWorkRequest tokenTestWorkRequest) {
        initComponents();
        this.tokenTestWorkRequest = tokenTestWorkRequest;
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        jLabelEnterpriseName.setText(enterprise.getName());
        txtFiveHundredNotes.setText(String.valueOf(tokenTestWorkRequest.getFiveHunderdNotes()));
        txtThousandNotes.setText(String.valueOf(tokenTestWorkRequest.getThousandNotes()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProcessRequest = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabelEnterpriseName = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFiveHundredNotes = new javax.swing.JTextField();
        txtThousandNotes = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProcessRequest.setBackground(new java.awt.Color(255, 255, 255));
        btnProcessRequest.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnProcessRequest.setText("Complete Transaction");
        btnProcessRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessRequestActionPerformed(evt);
            }
        });
        add(btnProcessRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 240, 60));

        backJButton.setBackground(new java.awt.Color(255, 255, 255));
        backJButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 120, 50));

        jLabelEnterpriseName.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEnterpriseName.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabelEnterpriseName.setText("<value>");
        add(jLabelEnterpriseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 340, 60));

        enterpriseLabel.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 190, 60));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("500 notes :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 100, 40));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("1000 notes :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 100, 50));
        add(txtFiveHundredNotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 150, 40));

        txtThousandNotes.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        add(txtThousandNotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 150, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcessRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessRequestActionPerformed
        tokenTestWorkRequest.getDenomination().setThousandNote(Integer.parseInt(txtThousandNotes.getText()));
        tokenTestWorkRequest.getDenomination().setFiveHundredNote(Integer.parseInt(txtFiveHundredNotes.getText()));
        tokenTestWorkRequest.setStatus("Completed");
        tokenTestWorkRequest.setReceiver(userAccount);
        int a= 0,b= 0;
        int amount =0;
        try {
            a = Integer.parseInt(txtFiveHundredNotes.getText());
            b = Integer.parseInt(txtThousandNotes.getText());
            amount = a*500 + b*1000;
            if(a<0 || b<0){
                JOptionPane.showMessageDialog(this, "Please enter amount greater than 0.");
            }
            else if ((amount > 0 && amount < 10000 )|| tokenTestWorkRequest.isDeposit()) {
                tokenTestWorkRequest.setAmount(amount);
                tokenTestWorkRequest.setReceiver(userAccount);
                tokenTestWorkRequest.setFiveHunderdNotes(a);
                tokenTestWorkRequest.setThousandNotes(b);
                JOptionPane.showMessageDialog(null, "Transaction Successfull");
            } 
            else if (amount > 10000 && !tokenTestWorkRequest.isDeposit()) {
                JOptionPane.showMessageDialog(this, "Exchange not allowed over 10000. Please attempt a deposit.");
            } 
            else{
                JOptionPane.showMessageDialog(this, "Please enter proper amount");
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please enter proper amount");
            return;
        } 
          
        if (tokenTestWorkRequest.getAmount() > 10000 && tokenTestWorkRequest.isDeposit()) {
            EcoSystem business = EcoSystem.getInstance();
            for (Network network : business.getNetworkList()) {
                if (network.getEnterpriseDirectory().getEnterpriseList().contains(enterprise)) {
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof IncomeTaxOrganization) {
                            organization.getWorkQueue().getWorkRequestList().add(tokenTestWorkRequest);
                        }
                    }
                }
            }
        }


    }//GEN-LAST:event_btnProcessRequestActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnProcessRequest;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelEnterpriseName;
    private javax.swing.JTextField txtFiveHundredNotes;
    private javax.swing.JTextField txtThousandNotes;
    // End of variables declaration//GEN-END:variables
}
