/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ManagerRole;

import Business.EcoSystem;
import Business.Enterprise.BankEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.EmployeeOrganization;
import Business.Organization.FederalOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BankToFederalBankWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author keval
 */
public class RequestToFedralJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    EcoSystem business;
    Enterprise enterprise;
    UserAccount userAccount;

    public RequestToFedralJPanel(JPanel userProcessContainer, EcoSystem business, Enterprise enterprise, UserAccount userAccount) {
        initComponents();
        jLabelEnterpriseName.setText(enterprise.getName());
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        
    }

  public void calculateTotalAmount() {
          Date input = jCalendarComboBox1.getDate();
        LocalDate selectedDate= input.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        System.out.println(selectedDate);
        
        int depositTotal=0; int exchangeTotal = 0;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof EmployeeOrganization) {
                for (WorkRequest workRequest : organization.getWorkQueue().getWorkRequestList()) {
                    if (workRequest.getStatus().equalsIgnoreCase("completed")) {
                        if(workRequest.isDeposit()==true&&workRequest.getRequestDate().equals(selectedDate)){
                        depositTotal = depositTotal + workRequest.getAmount();
                        }
                        if(workRequest.isDeposit()==false&&workRequest.getRequestDate().equals(selectedDate)){
                            exchangeTotal=exchangeTotal+workRequest.getAmount();
                        }
                        }
                }
            }
        }
        txtDepositAmmount.setText(String.valueOf(depositTotal));
        txtExchangeAmmount.setText(String.valueOf(exchangeTotal));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jCalendarComboBox1 = new de.wannawork.jcalendar.JCalendarComboBox();
        txtDepositAmmount = new javax.swing.JTextField();
        txtExchangeAmmount = new javax.swing.JTextField();
        jLabelEnterpriseName = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Deposit Ammount:");

        btnSubmit.setBackground(new java.awt.Color(255, 255, 255));
        btnSubmit.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnSubmit.setText("Submit To Federal Bank");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Exchange Ammount:");

        jCalendarComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCalendarComboBox1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        txtDepositAmmount.setEditable(false);
        txtDepositAmmount.setBackground(new java.awt.Color(204, 204, 204));
        txtDepositAmmount.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtDepositAmmount.setEnabled(false);
        txtDepositAmmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDepositAmmountActionPerformed(evt);
            }
        });

        txtExchangeAmmount.setEditable(false);
        txtExchangeAmmount.setBackground(new java.awt.Color(204, 204, 204));
        txtExchangeAmmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExchangeAmmountActionPerformed(evt);
            }
        });

        jLabelEnterpriseName.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEnterpriseName.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabelEnterpriseName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEnterpriseName.setText("jLabel5");

        jButton1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton1.setText("Display");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(523, 523, 523)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtExchangeAmmount, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDepositAmmount, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(641, 641, 641)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(485, 485, 485)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCalendarComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelEnterpriseName, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(466, 466, 466))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabelEnterpriseName, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCalendarComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDepositAmmount, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtExchangeAmmount, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(500, 500, 500))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:

        BankToFederalBankWorkRequest bankToFederalBankWorkRequest = new BankToFederalBankWorkRequest();
        Date input = jCalendarComboBox1.getDate();
        LocalDate date = input.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        bankToFederalBankWorkRequest.setRequestDate(date);

        bankToFederalBankWorkRequest.setAmount(Integer.parseInt(txtExchangeAmmount.getText()));

        bankToFederalBankWorkRequest.setAmountToPickUp(Integer.parseInt(txtDepositAmmount.getText()));

        bankToFederalBankWorkRequest.setBankEnterprise((BankEnterprise) enterprise);

        for (Network network : business.getNetworkList()) {
            if (network.getEnterpriseDirectory().getEnterpriseList().contains(enterprise)) {
                for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof FederalOrganization) {
                            organization.getWorkQueue().getWorkRequestList().add(bankToFederalBankWorkRequest);
                            JOptionPane.showMessageDialog(null, "Request submitted succesfully", "Complete!", JOptionPane.PLAIN_MESSAGE);
                            bankToFederalBankWorkRequest.setStatus("Sent");
                            break;
                        }
                    }
                }
            }
        }

        ManagerWorkAreaJPanel managerWorkAreaJPanel = new ManagerWorkAreaJPanel(userProcessContainer, enterprise, business, userAccount);
        userProcessContainer.add("managerWorkAreaJPanel", managerWorkAreaJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtExchangeAmmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExchangeAmmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExchangeAmmountActionPerformed

    private void txtDepositAmmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepositAmmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDepositAmmountActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        calculateTotalAmount();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton jButton1;
    private de.wannawork.jcalendar.JCalendarComboBox jCalendarComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelEnterpriseName;
    private javax.swing.JTextField txtDepositAmmount;
    private javax.swing.JTextField txtExchangeAmmount;
    // End of variables declaration//GEN-END:variables
}
