/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.IncomeTaxOfficerRole;

import Business.EcoSystem;
import Business.Enterprise.BankEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.EmployeeOrganization;
import Business.Organization.IncomeTaxOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.Color;
import java.time.LocalDate;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author keval
 */
public class BarChart extends javax.swing.JPanel {

    /**
     * Creates new form BarChart
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private IncomeTaxOrganization incomeTaxOrganization;
    private Enterprise enterprise;
    private EcoSystem business;
    private LocalDate startDate;
    private LocalDate endDate;
    
    

    public BarChart(JPanel userProcessContainer, UserAccount account, IncomeTaxOrganization incomeTaxOrganization, Enterprise enterprise,EcoSystem business,LocalDate startdate,LocalDate endDate) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.incomeTaxOrganization=incomeTaxOrganization;
        this.enterprise=enterprise;
        this.business=business;
        this.startDate=startdate;
        this.endDate=endDate;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Report"));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jButton1.setText("Bar chart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 303, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         int a[]=new int[7];
         int i=0;
        for(Network network:business.getNetworkList()){
            for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseList()){
                if(enterprise instanceof BankEnterprise){
                    for(Organization organization:enterprise.getOrganizationDirectory().getOrganizationList()){
                        if(organization instanceof EmployeeOrganization){
                            for(WorkRequest workRequest:organization.getWorkQueue().getWorkRequestList()){
                                if(workRequest.getStatus().equalsIgnoreCase("completed")){
                                    if(workRequest.getRequestDate().getDayOfMonth()<=endDate.getDayOfMonth() && workRequest.getRequestDate().getDayOfMonth()>=startDate.getDayOfMonth()&& workRequest.isDeposit() ){
                                        
                                        a[workRequest.getRequestDate().getDayOfMonth()-startDate.getDayOfMonth()]+=workRequest.getAmount();
                                        
                                        
                                        
                                    }
                                    
                                }
                            }
                        }
                    }
                }
            }
        }
        
        
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(a[0], "date", "deposit");
        System.out.println(a[0]);
        dataset.setValue(a[1], "date1", "deposit1");
        dataset.setValue(a[2], "date2", "deposit2");
        dataset.setValue(a[3], "date3", "deposit3");
        JFreeChart jchar = ChartFactory.createBarChart("Incom tax", "date", "Deposit", dataset, PlotOrientation.VERTICAL, true, true,false);
        
        CategoryPlot plot = jchar.getCategoryPlot();
        plot.setRangeGridlinePaint(Color.BLACK);
        
        ChartFrame chartf = new ChartFrame("Student Recrd", jchar, true);
        chartf.setVisible(true);
        chartf.setSize(500,400);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
