/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.EcoSystem;
import Business.Enterprise.BankEnterprise;
import Business.Organization.CustomerOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.TokenTestWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author keval
 */
public class CustomerTransactionJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private CustomerOrganization customerOrganization;
    private BankEnterprise bankEnterprise;
    private TokenTestWorkRequest tokenTestWorkRequest;
    /**
     * Creates new form CustomerTranaction
     */
   

    public CustomerTransactionJPanel(JPanel userProcessContainer, UserAccount userAccount, CustomerOrganization customerOrganization, EcoSystem business, BankEnterprise bankEnterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.business = business;
        this.bankEnterprise=bankEnterprise;
        this.tokenTestWorkRequest=new TokenTestWorkRequest();
        this.customerOrganization = (CustomerOrganization)customerOrganization; //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transactionType = new javax.swing.ButtonGroup();
        jRadioButtonDeposit = new javax.swing.JRadioButton();
        jRadioButtonExchange = new javax.swing.JRadioButton();
        btnNext = new javax.swing.JButton();
        selectTransctiontype = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jRadioButtonDeposit.setBackground(new java.awt.Color(255, 255, 255));
        transactionType.add(jRadioButtonDeposit);
        jRadioButtonDeposit.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jRadioButtonDeposit.setText("Deposit");

        jRadioButtonExchange.setBackground(new java.awt.Color(255, 255, 255));
        transactionType.add(jRadioButtonExchange);
        jRadioButtonExchange.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jRadioButtonExchange.setText("Exchange");

        btnNext.setBackground(new java.awt.Color(255, 255, 255));
        btnNext.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        btnNext.setText("Next");
        btnNext.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        selectTransctiontype.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        selectTransctiontype.setText("Select Transaction Type");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(458, 458, 458)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(selectTransctiontype, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jRadioButtonDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addComponent(jRadioButtonExchange))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(545, 545, 545)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(727, 727, 727))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(selectTransctiontype, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonExchange, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(500, 500, 500))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        if(isAnyOptionSelected()){
            this.tokenTestWorkRequest.setDeposit(getSelectedOption());
            CustomerWorkAreaJPanel customerWorkAreaJPanel = new CustomerWorkAreaJPanel(userProcessContainer,userAccount,customerOrganization,business,tokenTestWorkRequest,bankEnterprise);
            userProcessContainer.add("processWorkRequestJPanel",customerWorkAreaJPanel );
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        else
            JOptionPane.showMessageDialog(null, "Please select an option", "No selection detected", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnNextActionPerformed
    
    
    private boolean isAnyOptionSelected() {
        if(jRadioButtonDeposit.isSelected() || jRadioButtonExchange.isSelected()) return true;
        else return false;
    }
    
    
    public boolean getSelectedOption(){
        if(jRadioButtonDeposit.isSelected()) return true;
        else return false;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JRadioButton jRadioButtonDeposit;
    private javax.swing.JRadioButton jRadioButtonExchange;
    private javax.swing.JLabel selectTransctiontype;
    private javax.swing.ButtonGroup transactionType;
    // End of variables declaration//GEN-END:variables
}
